### ISSUE TITLE
集成阿里云ons时出现问题 我项目使用了Netty5 而rocketMq 貌似用的是netty4 出现异常

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/RocketMQ#100]
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.channel.nio.NioEventLoopGroup.<init>(ILjava/util/concurrent/ThreadFactory;)V
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.<init>(NettyRemotingClient.java:254)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.<init>(MQClientAPIImpl.java:97)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.<init>(MQClientInstance.java:152)
	at com.alibaba.rocketmq.client.impl.MQClientManager.getAndCreateMQClientInstance(MQClientManager.java:53)
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:698)
	at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:363)
	at com.aliyun.openservices.ons.api.impl.rocketmq.ConsumerImpl.start(ConsumerImpl.java:68)
	at com.aliyun.openservices.ons.demo.ConsumerTest.main(ConsumerTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

貌似是jar包版本引起的 这种问题该如何解决呢

**Comment by vongosling** [comment]
Netty4 and Netty5 seems to not be co-exist.so, in case of some unknown errors,you‘d better return to netty4

**Comment by vongosling** [comment]
Netty4 and Netty5 didn’t seem to be co-exist.so, in case of some unknown errors,you‘d better return to netty4

**Comment by xiaolongyuan** [comment]
是的 切回 netty4 就可以运行了，谢谢

**Comment by vintagewang** [comment]
@xiaolongyuan   恩   现在netty 4和5  兼容性不够好， 目前还没有更好的方式能解决， netty5还处于beta阶段， 不建议使用。

**Comment by xiaolongyuan** [comment]
阿里 ons 使用 例如 java的sdk ons-example 有文档么

**Comment by vintagewang** [comment]
http://docs.aliyun.com/?spm=5176.7400025.9.6.W5F6Ap#/ons/quick-start/send
