### ISSUE TITLE
Can not start Name Server

### ISSUE THREAD

**Issue by imqishi** [alibaba/RocketMQ#103]
There is something wrong,  when I "cat nohup.out" , it shows:
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/rocketmq/namesrv/NamesrvStartup
Caused by: java.lang.ClassNotFoundException: com.alibaba.rocketmq.namesrv.NamesrvStartup
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: com.alibaba.rocketmq.namesrv.NamesrvStartup.  Program will exit.
Could someone help me?

**Comment by lizhanhui** [comment]
Checkout your classpath.

**Comment by sheaye** [comment]
Start the mqnamesrv.exe of the assembled package, not the source package.
