### ISSUE TITLE
求解答，经常报com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout

### ISSUE THREAD

**Issue by hbyscpp** [alibaba/RocketMQ#143]
客户端不定时报超时异常，网络正常，broker压力不大，采用 多master和多slave方式，对应的时间点broker上也没发现异常

**Comment by Lihuanghe** [comment]
粘贴全部异常信息

**Comment by hbyscpp** [comment]
2015-09-07 15:43:21.969 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:4
2:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@363cf55c[clientId=867146020010990,gpsTime=1441505730693,gpsPosType=ThreeDim_POS,pdop=2.3,sa
telliteNum=6,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to roc
ketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]
2015-09-07 15:43:21.970 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:4
2:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@7c455765[clientId=867146020010990,gpsTime=1441505727706,gpsPosType=ThreeDim_POS,pdop=2.3,sa
telliteNum=6,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to roc
ketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]
2015-09-07 15:43:21.970 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:4
2:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@7d39af6c[clientId=867146020010990,gpsTime=1441505722708,gpsPosType=ThreeDim_POS,pdop=1.7,sa
telliteNum=7,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to roc
ketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
        at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]

**Comment by hbyscpp** [comment]
心跳包也超时

**Comment by tanweii163** [comment]
/**
 * 定期检测客户端连接，清除不活动的连接
 * 
 * @author shijia.wxr<vintage.wang@gmail.com>
 * @since 2013-7-26
 */
public class ClientHousekeepingService implements ChannelEventListener {

客户端连接有问题，网络闪断什么

**Comment by hbyscpp** [comment]
要么是连接master broker超时，要么是连接slave broker连接超时。这台机器上其它程序 都不报网络错误

**Comment by hbyscpp** [comment]
无规律的这种，我们是测试环境，压力不大。一般也就一分钟后自行恢复。

**Comment by Lihuanghe** [comment]
帮你重贴下异常信息：

```

2015-09-07 15:43:21.969 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:42:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@363cf55[clientId=867146020010990,gpsTime=1441505730693,gpsPosType=ThreeDim_POS,pdop=2.3,sa
telliteNum=6,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to rocketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, #48
at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]
2015-09-07 15:43:21.970 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:42:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@7c45576[clientId=867146020010990,gpsTime=1441505727706,gpsPosType=ThreeDim_POS,pdop=2.3,sa
telliteNum=6,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to rocketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, #48
at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]
2015-09-07 15:43:21.970 ClientHouseKeepingService ERROR c.y.y.m.d.service.TopicExecutor---send msg :header version=1.0,seq=24,clientId=867146020010990,time=2015-09-07T15:42:26.000+08:00,type=2,bodylength=164,body com.yuntu.ytdrive.mq.message.GPSEvent@7d39af6[clientId=867146020010990,gpsTime=1441505722708,gpsPosType=ThreeDim_POS,pdop=1.7,sa
telliteNum=7,longitude=106.57196166666667,latitude=29.508378333333333,longitudeDirect=1,latitudeDirect=1,height=368.0,trueNorthDirect=0.0,northDirect=0.0,speed=0.0] to rocketmq.
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 10000ms
For more information, please visit the url, #48
at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344) [rocketmq-client-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331) [rocketmq-remoting-3.2.6.jar!/:na]
at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309) [rocketmq-remoting-3.2.6.jar!/:na]
at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.7.0_60]
at java.util.TimerThread.run(Timer.java:505) [na:1.7.0_60]

```

**Comment by Celthi** [comment]
也经常报这个错误，环境，单机，rocketMQ 3.2.6, 部署在同一台机器上。
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 3000ms
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$1.operationComplete(MQClientAPIImpl.java:344)
	at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62)
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:331)
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$5.run(NettyRemotingClient.java:309)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by Lihuanghe** [comment]
@Celthi 我也遇到过此问题，如果部署是多台机器就没问题，在linux单机也没问题。抓包发现window环境系统发网络包总是延迟5s才发。原因不详。

**Comment by Celthi** [comment]
我是在linux单机，用xshell登陆运行脚本@Lihuaghe
