### ISSUE TITLE
已经正常进行发布订阅，但使用mqadmin异常

### ISSUE THREAD

**Issue by ronyongxian** [alibaba/RocketMQ#152]
sh mqadmin clusterList
com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:641)
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1241)
        at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:258)
        at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:184)
        at com.alibaba.rocketmq.tools.command.cluster.ClusterListSubCommand.printClusterBaseInfo(ClusterListSubCommand.java:73)
        at com.alibaba.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:246)
        at com.alibaba.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:180)
        at com.alibaba.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:125)

使用双主模式，nameserver与broker同机。
貌似连接nameserver异常，但已正常运作，不知为何，求教。

**Comment by lizhanhui** [comment]
You need to specify the name-server address while executing this command.

**Comment by ronyongxian** [comment]
thanks a lot, i thought it will connect to any name server by itself. by the way, do you know any monitor or console on the rocket mq, excluding the mqadmin?

**Comment by lizhanhui** [comment]
Try this one: https://github.com/rocketmq/rocketmq-console/

We'll also release a auto-pilot tool for RocketMQ shortly.
