### ISSUE TITLE
权限验证失败

### ISSUE THREAD

**Issue by jessonlv** [alibaba/RocketMQ#160]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: com.aliyun.openservices.ons.api.impl.authority.exception.AuthenticationException: valid permission failed., com.alibaba.ons.open.auth.validator.PermissionValidator.aliyun(PermissionValidator.java:66)
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processPullResponse(MQClientAPIImpl.java:521)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.access$100(MQClientAPIImpl.java:80)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:476)
	at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62)
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-10-02 00:36:29,721 WARN RocketmqClient(503) - execute the pull request exception

**Comment by vintagewang** [comment]
已回复邮件， 请查收。

**Comment by bjhetang** [comment]
您好！我也遇见了一样的问题，请问怎么解决，不停地打日志，磁盘有爆掉的危险

**Comment by wangjingfei** [comment]
遇到了同样的问题，几分钟1G的磁盘。。。

**Comment by jackiehff** [comment]
请问如何解决的？

**Comment by jackiehff** [comment]
@vintagewang

**Comment by wangjingfei** [comment]
Sorry，我的那个发生的时候是因为我自己的代码抛了异常，代码的异常被封装成了权限验证失败。。。
