### ISSUE TITLE
The consumer group has been created before

### ISSUE THREAD

**Issue by ronyongxian** [alibaba/RocketMQ#162]
com.alibaba.rocketmq.client.exception.MQClientException: The consumer group[t11] has been created before, specify another name please.
See #40 for further details.
at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:714)
at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:365)

这个好像是bug，因为只是调用了
DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("t11");
在同一个客户端新增consumer

**Comment by vongosling** [comment]
you can't say as if.reproduce it and paste some context~
