### ISSUE TITLE
benchmark下的tproducer.sh脚本直接运行会报错

### ISSUE THREAD

**Issue by jiangjingjiu** [alibaba/RocketMQ#180]
我是运维人员，想简单测试下rocketmq becnhmark的性能，但发现benchmark目录下的tproducer.sh无法正常运行，报如下错误：
sh tproducer.sh 
: command not found2: 
"xception in thread "main" java.lang.NumberFormatException: For input string: "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:481)
        at java.lang.Integer.parseInt(Integer.java:527)
        at com.alibaba.rocketmq.example.benchmark.TransactionProducer.main(TransactionProducer.java:46)

有空请帮忙看看，谢谢~

**Comment by jiangjingjiu** [comment]
文件格式问题
