### ISSUE TITLE
这个错误怎么解决？

### ISSUE THREAD

**Issue by ltlt000000** [alibaba/RocketMQ#187]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: com.aliyun.openservices.ons.api.impl.authority.exception.AuthenticationException: valid permission failed., com.alibaba.ons.open.auth.validator.PermissionValidator.aliyun(PermissionValidator.java:66)
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.consumerSendMessageBack(MQClientAPIImpl.java:1053)
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.sendMessageBack(DefaultMQPushConsumerImpl.java:631)
	at com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService.sendMessageBack(ConsumeMessageConcurrentlyService.java:211)
	at com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService.processConsumeResult(ConsumeMessageConcurrentlyService.java:271)
	at com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:180)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/108
