### ISSUE TITLE
netty5版本，客户端的Remoting模块有异常

### ISSUE THREAD

**Issue by 879913935** [alibaba/RocketMQ#188]
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.bootstrap.Bootstrap.channel(Ljava/lang/Class;)Lio/netty/bootstrap/AbstractBootstrap;
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.start(NettyRemotingClient.java:281)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.start(MQClientAPIImpl.java:167)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.start(MQClientInstance.java:179)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:192)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.start(DefaultMQProducerImpl.java:160)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.start(DefaultMQProducer.java:76)

**Comment by Lihuanghe** [comment]
怎么会有netty5? 官方只支持netty4啊
