### ISSUE TITLE
错误：service not available now, maybe disk full, CL:  0.91 CQ:  0.91 INDEX:  0.91, maybe your broker machine memory too small.

### ISSUE THREAD

**Issue by cnJun** [alibaba/RocketMQ#195]
启动服务后，producer.send时，提示如下错误：

com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [31]ms, Topic: PushTopic, BrokersSent: [AnyX, null, null]
See https://github.com/alibaba/RocketMQ/issues/50 for further details.
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:578)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)
	at net.my.app.zt.service.test.MqProducer.main(MqProducer.java:24)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.91 CQ:  0.91 INDEX:  0.91, maybe your broker machine memory too small.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:404)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:308)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:289)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:679)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:500)
	... 4 more

**Comment by hh3755** [comment]
也出现过类似情况,使用下述命令查看硬盘使用,删除掉不需要的东西.
`du -sh /`

**Comment by yinbin1yd** [comment]
这个问题把服务器与客户端的版本改成一致的就行了
