### ISSUE TITLE
发送重试超时

### ISSUE THREAD

**Issue by lindzh** [alibaba/RocketMQ#201]
`
**com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [3001]ms, Topic: adjsms, BrokersSent: [broker-1, null, null]
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:590)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1026)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:122)**
`

**Comment by lindzh** [comment]
CPU和内存都正常，消息量没有明显增加，网络延迟不大，为什么会超时3秒

**Comment by yinbin1yd** [comment]
像这种问题一般是服务端与客户端版本不一致

**Comment by vongosling** [comment]
refer to https://github.com/alibaba/RocketMQ/issues/108
