### ISSUE TITLE
jdk1.7环境下broker启动不了

### ISSUE THREAD

**Issue by zcgewu** [alibaba/RocketMQ#205]
[root@iZ23vovs50mZ bin]# sh mqbroker -n "127.0.0.1:9876" -c ../conf/2m-noslave/broker-a.properties 
load config properties file OK, ../conf/2m-noslave/broker-a.properties
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at com.alibaba.rocketmq.store.schedule.ScheduleMessageService.start(ScheduleMessageService.java:117)
        at com.alibaba.rocketmq.store.DefaultMessageStore.start(DefaultMessageStore.java:311)
        at com.alibaba.rocketmq.broker.BrokerController.start(BrokerController.java:531)
        at com.alibaba.rocketmq.broker.BrokerStartup.start(BrokerStartup.java:267)
        at com.alibaba.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:78)
[root@iZ23vovs50mZ bin]# java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
[root@iZ23vovs50mZ bin]# echo $JAVA_HOME
/usr/local/jdk1.7.0_80

**Comment by lizhanhui** [comment]
你显然是用jdk8编译打得包. HotSpot Java 8 修改了HashMap的实现方式.

**Comment by vongosling** [comment]
KeySetView是1.8引入的内部静态类，请自查

**Comment by zcgewu** [comment]
@lizhanhui @vongosling 谢谢二位。windows系统的jdk还的确是1.8的。

**Comment by javafx2010** [comment]
那怎么办咧？
