### ISSUE TITLE
Rocketmq测试发现——java.lang.AbstractMethodError错误

### ISSUE THREAD

**Issue by bwzhang2011** [alibaba/RocketMQ#207]
调测ROKCETMQ中发现一个非常奇怪的问题
前提：
1. 【A方式】JDK环境为1.8（NETTY为4.1.0.CR3）， 然后 2台机器部署2master-2slave集群 2台机器构建namesvr，集群连接到namesvr
2. 【B方式】与上近似，2台机器，只是namesvr的环境在master-salve的机器上（1台一个）
经测试：
启动和日志两种方式都没有问题，但进行数据的发送和消费的时候，A方式存在问题，报错如下：
1. 服务端（来自broker.log)
java.lang.AbstractMethodError: com.alibaba.rocketmq.broker.pagecache.ManyMessageTransfer.touch(Ljava/lang/Object;)Lio/netty/util/ReferenceCounted;
	at io.netty.util.ReferenceCountUtil.touch(ReferenceCountUtil.java:73)
	at io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:272)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1186)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:286)
	at com.alibaba.rocketmq.broker.processor.PullMessageProcessor.processRequest(PullMessageProcessor.java:409)
	at com.alibaba.rocketmq.broker.processor.PullMessageProcessor.processRequest(PullMessageProcessor.java:80)
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract$1.run(NettyRemotingAbstract.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

且这个错误一直持续下去

2. 而消费者的错误日志为
com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 30000ms
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:567) ~[rocketmq-client-patch-3.2.6.jar:?]
	at com.alibaba.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:62) ~[rocketmq-remoting-3.2.6.jar:?]
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.scanResponseTable(NettyRemotingAbstract.java:338) ~[rocketmq-remoting-3.2.6.jar:?]
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient$2.run(NettyRemotingClient.java:299) ~[rocketmq-remoting-3.2.6.jar:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) ~[?:1.8.0_51]

个人判断，消费者抛出的异常跟BROKER的异常有关（我更新回NETTY4.0.34的FINAL也还是不行）
但不清楚为什么原因——追溯代码（PullMessageProcessor中Line408）
 FileRegion fileRegion =
                            new ManyMessageTransfer(response.encodeHeader(getMessageResult
                                .getBufferTotalSize()), getMessageResult);

channel.writeAndFlush(fileRegion). //省略

——这块写入fileRegin的时候就报错（但不知道原因）、而且一直持续下去；此外，消费者端报错的
“com.alibaba.rocketmq.client.exception.MQClientException: wait response timeout 30000ms”
也无法理解，response timeout异常有哪些原因呢。

——我反复调测（部署的目录结构完全一样），按照B方式则没有问题。

**Comment by bwzhang2011** [comment]
@vintagewang, 有时间能否帮忙看一下。消息是能够发到MQ上，但是消费就出错了。

**Comment by bwzhang2011** [comment]
@vintagewang, 把A环境切换指向B环境配置的namesvr经反复调测后（具体不清楚什么原因后又调整好了）

**Comment by bwzhang2011** [comment]
@vongosling, 若升级netty到4.1,会重现上述问题。未来rocketmq是否考虑兼容支持netty到4.1版本

**Comment by vongosling** [comment]
must

**Comment by bwzhang2011** [comment]
@vongosling, 确认一下rocketmq当前是否与netty4.1不兼容（从我这边的看到的现象），其次能否指出一下相关原因（为兼容4.1做准备）

**Comment by bwzhang2011** [comment]
@vongosling, does current rocketmq branch like 3.4.6 or afterwards solve the compatible problem with netty4.1 ?

**Comment by vongosling** [comment]
which broker version,3.4.6? please use the latest version.BTW, in the few days later,we will release the latest version 3.5.*.
