### ISSUE TITLE
gecko发送响应失败

### ISSUE THREAD

**Issue by muyunisawesome** [alibaba/RocketMQ#255]
[INFO] [GetProcess-1-thread-64] 05-13 17:06:54,714 [DefaultConnection] - 此session的流量: 983457771
[ERROR] [GetProcess-1-thread-64] 05-13 17:06:54,715 [RemotingUtils] - 发送响应失败
com.taobao.gecko.service.exception.NotifyRemotingException: 发送消息失败，超过流量限制[804872192字节]
        at com.taobao.gecko.service.impl.DefaultConnection.checkFlow(DefaultConnection.java:253)
        at com.taobao.gecko.service.impl.DefaultConnection.response(DefaultConnection.java:475)
        at com.ai.usb.common.network.RemotingUtils.response(RemotingUtils.java:27)
        at com.ai.usb.server.network.GetProcessor.handleRequest(GetProcessor.java:50)
        at com.ai.usb.server.network.GetProcessor.handleRequest(GetProcessor.java:23)
        at com.taobao.gecko.service.impl.GeckoHandler$ProcessorRunner.run(GeckoHandler.java:82)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)

我现在是getMessageSessionFactory().createConsumer(）。创建了19个consumer。并发取消息，每个consumer使用get方法同步取的
consumer.get(systemConfig.getTopic(), Constant.partition, offset, systemConfig.getMaxSize());
配置的是14M

请问是怎么回事啊

**Comment by vongosling** [comment]
请确定com.taobao.gecko.service.exception.NotifyRemotingException类来源jar包

**Comment by muyunisawesome** [comment]
gecko-1.1.4.jar
