### ISSUE TITLE
mq报错：Broken pipe

### ISSUE THREAD

**Issue by muyunisawesome** [alibaba/RocketMQ#268]
java.io.IOException: Broken pipe
        at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
        at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:405)
        at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:506)
        at com.taobao.gecko.core.core.impl.FileWriteMessage.transferTo(FileWriteMessage.java:160)
        at com.taobao.gecko.core.core.impl.FileWriteMessage.write(FileWriteMessage.java:131)
        at com.taobao.gecko.core.nio.impl.NioTCPSession.doRealWrite(NioTCPSession.java:98)
        at com.taobao.gecko.core.nio.impl.NioTCPSession.writeToChannel0(NioTCPSession.java:126)
        at com.taobao.gecko.core.nio.impl.AbstractNioSession.writeToChannel(AbstractNioSession.java:157)
        at com.taobao.gecko.core.nio.impl.AbstractNioSession.onWrite(AbstractNioSession.java:210)
        at com.taobao.gecko.core.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:505)
        at com.taobao.gecko.core.nio.impl.SocketChannelController.dispatchWriteEvent(SocketChannelController.java:92)
        at com.taobao.gecko.core.nio.impl.NioController.onWrite(NioController.java:231)
        at com.taobao.gecko.core.nio.impl.Reactor.dispatchEvent(Reactor.java:478)
        at com.taobao.gecko.core.nio.impl.Reactor.processSelectedKeys(Reactor.java:312)
        at com.taobao.gecko.core.nio.impl.Reactor.run(Reactor.java:255)

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
