### ISSUE TITLE
consumer服务器异常停机，Default Push模式，重启后启动失败，报json解析错误

### ISSUE THREAD

**Issue by victorydsk** [alibaba/RocketMQ#269]
com.alibaba.rocketmq.client.exception.MQClientException: readLocalOffset Exception, maybe fastjson version too low
See https://github.com/alibaba/RocketMQ/issues/45 for further details.
        at com.alibaba.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffsetBak(LocalFileOffsetStore.java:196)
        at com.alibaba.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffset(LocalFileOffsetStore.java:179)
        at com.alibaba.rocketmq.client.consumer.store.LocalFileOffsetStore.load(LocalFileOffsetStore.java:68)
        at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:692)
        at com.alibaba.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:365)
        at com.obd.parser.MainThread.main(MainThread.java:99)
Caused by: com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:232)
        at com.alibaba.fastjson.parser.deserializer.ASMJavaBeanDeserializer.parseRest(ASMJavaBeanDeserializer.java:100)
        at Fastjson_ASM_OffsetSerializeWrapper_1.deserialze(Unknown Source)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:551)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:251)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:227)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:186)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:304)
        at com.alibaba.rocketmq.remoting.protocol.RemotingSerializable.fromJson(RemotingSerializable.java:45)
        at com.alibaba.rocketmq.client.consumer.store.LocalFileOffsetStore.readLocalOffsetBak(LocalFileOffsetStore.java:192)
        ... 5 more

请问该如何解决这个问题，网上有人说是本地的json文件因为异常关机被破坏了，如何进行恢复？文件在什么位置？

**Comment by gaoyf** [comment]
你用的是广播消费？
路径是${user.home}/.rocketmq_offsets/${clientdId}/${groupName}/offsets.json

**Comment by victorydsk** [comment]
你好，是广播消费，找到路径了，谢谢



victorydsk@hotmail.com
 
发件人： gaoyf
发送时间： 2016-06-02 12:46
收件人： alibaba/RocketMQ
抄送： victorydsk; Author
主题： Re: [alibaba/RocketMQ] consumer服务器异常停机，Default Push模式，重启后启动失败，报json解析错误 (#269)
你用的是广播消费？
路径是${user.home}/.rocketmq_offsets/${clientdId}/${groupName}/offsets.json

**Comment by vongosling** [comment]
https://github.com/alibaba/RocketMQ/issues/270
