### ISSUE TITLE
运行过程中出现错误No topic route info in name server for the topic: xxxx

### ISSUE THREAD

**Issue by quchunhui** [alibaba/RocketMQ#294]
各位RocketMQ的大神们，
我在使用Storm消费RocketMQ的消息的过程中，本来好好的，有的时候更换一个消费组之后，
经常会下面的错误，从而导致无法消费消息，请问是什么原因引起的？

注：
Topic本身已经存在。并且已经被正常的消费过。

2016-07-07 17:50:59.546 RocketmqClient [WARN] updateTopicRouteInfoFromNameServer Exception
com.alibaba.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: status1
See https://github.com/alibaba/RocketMQ/issues/38 for further details.
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1315) ~[stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:573) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:549) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:1019) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:282) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:248) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:250) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:925) [stormjar.jar:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:49) [stormjar.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]

**Comment by gaoyf** [comment]
topic的路由信息是从nameserver查询的，而nameserver的topic路由信息是broker通过心跳传过去的。
如果查不到，我怀疑你的storm消费代码连接的nameserver上面没有这个topic的路由信息。

**Comment by quchunhui** [comment]
非常感谢专家的回答。按照您提供的思路，对代码和集群环境进行了检查。
发现，MQ的启动命令中指定的nameserver和代码中的配置存在出入所导致的。

启动命令中指定了一个nameserver。
nohup sh mqbroker -c ../conf/broker-a.properties -n xx.xx.xx.xx:9876 &
而代码中指定的两个nameserver。

非常感谢您的回答，解决了一直以来存在的疑惑。
