### ISSUE TITLE
auto start mqfiltersrv failed

### ISSUE THREAD

**Issue by zlqpzww** [alibaba/RocketMQ#348]
In the wiki , it says that set the broker's property -- filterServerNums=1 can let broker start the mqfiltersrv automatically . but in fact I did that but get a wrong log. So why this will happen?

Below is the broker log:

`2016-09-10 22:09:15 ERROR FilterServerManagerScheduledThread1 - callShell: readLine IOException, start /b C:\Applications\alibaba-rocketmq\alibaba-rocketmq-3.2.6\bin/..\bin\mqfiltersrv.exe -c C:\Applications\alibaba-rocketmq\alibaba-rocketmq-3.2.6\conf\2m-noslave\broker-a.properties -n localhost:9876

java.io.IOException: Cannot run program "start": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_101]
	at java.lang.Runtime.exec(Runtime.java:620) ~[na:1.8.0_101]
	at java.lang.Runtime.exec(Runtime.java:485) ~[na:1.8.0_101]
	at com.alibaba.rocketmq.broker.filtersrv.FilterServerUtil.callShell(FilterServerUtil.java:17) ~[rocketmq-broker-3.2.6.jar:na]
	at com.alibaba.rocketmq.broker.filtersrv.FilterServerManager.createFilterServer(FilterServerManager.java:117) [rocketmq-broker-3.2.6.jar:na]
	at com.alibaba.rocketmq.broker.filtersrv.FilterServerManager$1.run(FilterServerManager.java:74) [rocketmq-broker-3.2.6.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method) ~[na:1.8.0_101]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[na:1.8.0_101]
	at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[na:1.8.0_101]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_101]
	... 12 common frames omitted`

**Comment by Jaskey** [comment]
Do you have your script lies on your path of  RocectMQ home?

```
        if (RemotingUtil.isWindowsPlatform()) {
            return String.format("start /b %s\\bin\\mqfiltersrv.exe %s", //
                this.brokerController.getBrokerConfig().getRocketmqHome(),//
                config);
        }
        else {
            return String.format("sh %s/bin/startfsrv.sh %s", //
                this.brokerController.getBrokerConfig().getRocketmqHome(),//
                config);
        }
```

**Comment by zlqpzww** [comment]
我还是用中文说吧,不然描述不清楚.
我是把rocketmq的bin目录加入到path系统变量里面的,然后在任意路径上用mqbroker.exe -c path2configuration这样来启动的

**Comment by zhouxinyu** [comment]
As @Jaskey  said, could you please set the environment variable "ROCKETMQ_HOME" and  try again?

**Comment by zlqpzww** [comment]
@zhouxinyu I think the key reason is that java.lang.Runtime.exec function can not run "start". beacuse the start is a windows cmd.exe 's subcommand. As you can see the log 
> java.io.IOException: Cannot run program "start": CreateProcess error=2, 系统找不到指定的文件。

**Comment by zlqpzww** [comment]
by the way the version of rocketmq is v3.2.6

**Comment by vongosling** [comment]
please use the latest version to recur
