### ISSUE TITLE
3.5.8 commit offset warn and  printWaterMark error ( castRunnable exception  null point )  

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#366]
16-09-28 14:02:49 WARN PullMessageThread_35 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:57477, key=BenchmarkTest@benchmark_consumer_79, queueId=416, requestOffset=1023, storeOffset=1054
16-09-28 14:02:52 WARN ClientManageThread_16 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=224, requestOffset=1458, storeOffset=1459
16-09-28 14:02:52 WARN ClientManageThread_1 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=590, requestOffset=1451, storeOffset=1452
16-09-28 14:02:52 WARN ClientManageThread_9 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=384, requestOffset=1448, storeOffset=1449
16-09-28 14:02:52 WARN PullMessageThread_72 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:57477, key=BenchmarkTest@benchmark_consumer_79, queueId=942, requestOffset=1453, storeOffset=1454
16-09-28 14:02:52 WARN PullMessageThread_78 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:57477, key=BenchmarkTest@benchmark_consumer_79, queueId=787, requestOffset=1456, storeOffset=1457
16-09-28 14:02:52 WARN ClientManageThread_14 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=970, requestOffset=1454, storeOffset=1455
16-09-28 14:02:52 WARN ClientManageThread_14 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=554, requestOffset=1450, storeOffset=1451
16-09-28 14:02:52 WARN ClientManageThread_3 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=143, requestOffset=1459, storeOffset=1460
16-09-28 14:02:52 WARN ClientManageThread_6 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=817, requestOffset=1454, storeOffset=1455
16-09-28 14:02:52 WARN ClientManageThread_15 - [NOTIFYME]update consumer offset less than store. clientHost=10.126.88.100:13787, key=BenchmarkTest@benchmark_consumer_79, queueId=12, requestOffset=1454, storeOffset=1455
16-09-28 14:02:53 ERROR BrokerControllerScheduledThread1 - castRunnable exception, com.alibaba.rocketmq.broker.latency.FutureTaskExt
java.lang.ClassCastException: com.alibaba.rocketmq.broker.processor.PullMessageProcessor$2 cannot be cast to com.alibaba.rocketmq.remoting.netty.RequestTask
        at com.alibaba.rocketmq.broker.latency.BrokerFastFailure.castRunnable(BrokerFastFailure.java:104) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:422) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) [rocketmq-broker-3.5.8.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_45]
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-09-28 14:02:53 ERROR BrokerControllerScheduledThread1 - printWaterMark error.
java.lang.NullPointerException: null
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:423) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) ~[rocketmq-broker-3.5.8.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_45]
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

**Comment by a11123939** [comment]
java.lang.ClassCastException: com.alibaba.rocketmq.broker.processor.PullMessageProcessor$2 cannot be cast to com.alibaba.rocketmq.remoting.netty.RequestTask
        at com.alibaba.rocketmq.broker.latency.BrokerFastFailure.castRunnable(BrokerFastFailure.java:104) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:422) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) [rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) [rocketmq-broker-3.5.8.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_45]
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-09-28 14:02:53 ERROR BrokerControllerScheduledThread1 - printWaterMark error.
java.lang.NullPointerException: null
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:423) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) ~[rocketmq-broker-3.5.8.jar:na]
        at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) ~[rocketmq-broker-3.5.8.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [na:1.6.0_45]
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317) [na:1.6.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180) [na:1.6.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [na:1.6.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [na:1.6.0_45]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]

**Comment by lizhanhui** [comment]
Yes, the type-casting is buggy here.  Pull request is welcome.

**Comment by a11123939** [comment]
update consumer offset less than store. clientHost=10.126.88.100:57477, key=BenchmarkTest@benchmark_consumer_79, queueId=416 
client update offset less than store is also a problem.

**Comment by a11123939** [comment]
`boolean commitOffsetEnable = false;
        long commitOffsetValue = 0L;
        if (MessageModel.CLUSTERING == this.defaultMQPushConsumer.getMessageModel()) {
            commitOffsetValue =
                    this.offsetStore.readOffset(pullRequest.getMessageQueue(),
                        ReadOffsetType.READ_FROM_MEMORY);
            if (commitOffsetValue > 0) {
                commitOffsetEnable = true;
            }
        }

        String subExpression = null;
        boolean classFilter = false;
        SubscriptionData sd =
                this.rebalanceImpl.getSubscriptionInner().get(pullRequest.getMessageQueue().getTopic());
        if (sd != null) {
            if (this.defaultMQPushConsumer.isPostSubscriptionWhenPull() && !sd.isClassFilterMode()) {
                subExpression = sd.getSubString();
            }

            classFilter = sd.isClassFilterMode();
        }

        int sysFlag = PullSysFlag.buildSysFlag(//
            commitOffsetEnable, // commitOffset
            true, // suspend
            subExpression != null,// subscription
            classFilter // class filter
            );
        try {
            this.pullAPIWrapper.pullKernelImpl(//
                pullRequest.getMessageQueue(), // 1
                subExpression, // 2
                subscriptionData.getSubVersion(), // 3
                pullRequest.getNextOffset(), // 4
                this.defaultMQPushConsumer.getPullBatchSize(), // 5
                sysFlag, // 6
                commitOffsetValue,// 7
                BrokerSuspendMaxTimeMillis, // 8
                ConsumerTimeoutMillisWhenSuspend, // 9
                CommunicationMode.ASYNC, // 10
                pullCallback// 11
                );
        }`

client pull message have commit the offset .
 commit offset warn is not a big problem .
This problem occurs when high concurrency

**Comment by a11123939** [comment]
PullMessageProcessor excuteRequestWhenWakeup
` final RequestTask requestTask = new RequestTask(run, channel, request);
        this.brokerController.getPullMessageExecutor().submit(requestTask);
        //this.brokerController.getPullMessageExecutor().submit(run);`

fix the printWaterMark error ( castRunnable exception null point )

**Comment by bwzhang2011** [comment]
@vongosling, any update with such issue ?

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)

**Comment by Todd-start** [comment]
how to fix the issue .update consumer offset less than store.thx
