### ISSUE TITLE
FAQ: Topic不存在如何解决

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#38]
## 可能产生的原因
Broker关闭了自动创建Topic功能，导致Producer向Broker发送消息，服务器校验不通过

    autoCreateTopicEnable=false

## 解决方案一（推荐阿里内部用户使用）
到MetaQ控制台或者Spass控制台上申请Topic

## 解决方案二（推荐开源社区用户使用）
开启服务器自动创建Topic功能

    autoCreateTopicEnable=true

## 解决方案三（推荐开源社区用户使用）
使用命令行手工创建Topic到某台Broker

	sh mqadmin updateTopic -b "192.168.1.1:10911" -t Topic1 -r 10 -w 10

或

使用命令行手工创建Topic到某个集群

	sh mqadmin updateTopic -c cluster1 -t Topic1 -r 10 -w 10

**Comment by xiarilian12** [comment]
我在 windown 下做测试，启动了mqnamesrv.exe 和mqbroker.exe 也遇到这个问题，但是不知道方案二：开启服务器自动创建Topic功能 autoCreateTopicEnable=true 这个配置是在什么地方修改

**Comment by Shawyeok** [comment]
启动broker时可通过-c参数指定properties配置文件，不知道配置项可通过-m参数生成配置模板，这些内容在RocketMQ_userguide.pdf中都有详细说明

**Comment by 123321asdf** [comment]
用命令手工 创建 topic的时候sh mqadmin updateTopic -b "192.168.1.1:10911" -t Topic1 -r 10 -w 10 
报错：

connect to http://jmenv.tbsite.net:8080/rocketmq/nsaddr failed, maybe the domain name jmenv.tbsite.net not bind in /etc/hosts
See https://github.com/alibaba/RocketMQ/issues/57 for further details.
com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <192.168.1.44:10911> failed
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:645)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.createTopic(MQClientAPIImpl.java:317)
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdateTopicConfig(DefaultMQAdminExtImpl.java:166)
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdateTopicConfig(DefaultMQAdminExt.java:149)
	at com.alibaba.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:144)
	at com.alibaba.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:168)
	at com.alibaba.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:118)

**Comment by lizhanhui** [comment]
You need to specify name server address now that you have not specified it
via environment variable nor set up configuration server at given domain:
jmenv.tbsite.net.

**Comment by 123321asdf** [comment]
[root@ecs-029 bin]# sh mqadmin updateTopic -n 172.16.1.44:9876 -b 192.168.1.44:10911 -t LocationStatus -r 10 -w 10
com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <192.168.1.44:10911> failed
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:645)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.createTopic(MQClientAPIImpl.java:317)
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExtImpl.createAndUpdateTopicConfig(DefaultMQAdminExtImpl.java:166)
	at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt.createAndUpdateTopicConfig(DefaultMQAdminExt.java:149)
	at com.alibaba.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:144)
	at com.alibaba.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:168)
	at com.alibaba.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:118)

还是不行，指定nameserver没报 那个域名的错。topic 还是建不起来

**Comment by lizhanhui** [comment]
is your broker correctly configured, up and running?
Execute the following command to verify this:
 telnet 192.168.1.44 10911

**Comment by 123321asdf** [comment]
jps -v broker是运行的，10911 也是开着的，telnet可以联通
还是报错

**Comment by lizhanhui** [comment]
broker启动的时候， 配置了name server的地址了吗？ 能看到broker往name server注册topic路由信息么？

**Comment by stevenxian** [comment]
要是以上都不行 应该是本机连了vpn 在虚拟机参数上加上-Djava.net.preferIPv4Stack=true
