### ISSUE TITLE
阿里云ecs安装 rocketmq 失败，局域网测试服务器都是ok的，部署到阿里云esc出错是什么原因

### ISSUE THREAD

**Issue by zhangxiaoming** [alibaba/RocketMQ#380]
警告: doRebalance, mavinQConsumer db_update, get consumer id list failed
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.MQClientAPIImpl getTopicRouteInfoFromNameServer
警告: get Topic [db_delete] RouteInfoFromNameServer is not exist value
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.factory.MQClientInstance updateTopicRouteInfoFromNameServer
警告: updateTopicRouteInfoFromNameServer Exception
com.alibaba.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: db_delete
See http://docs.aliyun.com/cn#/pub/ons/faq/exceptions&topic_not_exist for further details.
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1114)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:475)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:370)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:978)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:258)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:221)
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:909)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:888)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:47)
	at java.lang.Thread.run(Thread.java:745)

十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl rebalanceByTopic
警告: doRebalance, mavinQConsumer, but the topic[db_delete] not exist.
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl rebalanceByTopic
警告: doRebalance, mavinQConsumer db_delete, get consumer id list failed
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.MQClientAPIImpl getTopicRouteInfoFromNameServer
警告: get Topic [db_insert] RouteInfoFromNameServer is not exist value
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.factory.MQClientInstance updateTopicRouteInfoFromNameServer
警告: updateTopicRouteInfoFromNameServer Exception
com.alibaba.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: db_insert
See http://docs.aliyun.com/cn#/pub/ons/faq/exceptions&topic_not_exist for further details.
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1114)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:475)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:370)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:978)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:258)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:221)
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:909)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:888)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:47)
	at java.lang.Thread.run(Thread.java:745)

十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl rebalanceByTopic
警告: doRebalance, mavinQConsumer, but the topic[db_insert] not exist.
十月 17, 2016 11:06:23 下午 com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl rebalanceByTopic
警告: doRebalance, mavinQConsumer db_insert, get consumer id list failed
^C[root@iZbp1gsnrlfzk0f9z5xp4wZ mavinq]#

**Comment by vongosling** [comment]
As the exception show,please check the network and topic can exist in your nameserver. please use english to resort to help next time.or if you have any question about aliyun ecs,please contact aliyun assistant
