### ISSUE TITLE
Broker can not start up, but it gives no information

### ISSUE THREAD

**Issue by XLILT** [alibaba/RocketMQ#388]
Once load the store failed, the broker can not start up. But there is no information about it. I can just debug it. That is a bad idea.

**Comment by lizhanhui** [comment]
Is there any log / hint showing why broker fails to start?

**Comment by vongosling** [comment]
please learn to how to ask a question https://github.com/alibaba/RocketMQ/issues/108

**Comment by XLILT** [comment]
I found some error log in store.log. It says

2016-10-31 15:49:54 ERROR main - load file C:\Users\Administrator\store\commitlog\00000000001073741824 error
java.io.IOException: Map failed
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:940) ~[na:1.8.0_101]
	at com.alibaba.rocketmq.store.MapedFile.<init>(MapedFile.java:71) ~[classes/:na]
	at com.alibaba.rocketmq.store.MapedFileQueue.load(MapedFileQueue.java:178) ~[classes/:na]
	at com.alibaba.rocketmq.store.CommitLog.load(CommitLog.java:79) [classes/:na]
	at com.alibaba.rocketmq.store.DefaultMessageStore.load(DefaultMessageStore.java:129) [classes/:na]
	at com.alibaba.rocketmq.broker.BrokerController.initialize(BrokerController.java:170) [classes/:na]
	at com.alibaba.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:210) [classes/:na]
	at com.alibaba.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:76) [classes/:na]
Caused by: java.lang.OutOfMemoryError: Map failed
	at sun.nio.ch.FileChannelImpl.map0(Native Method) ~[na:1.8.0_101]
	at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:937) ~[na:1.8.0_101]
	... 7 common frames omitted

This error loops about 760 000 lines.

I hope there is some information to show in the console .Thank you man.
@lizhanhui
