### ISSUE TITLE
ERROR RocketmqClient - pullKernelImpl exception 

### ISSUE THREAD

**Issue by a11123939** [alibaba/RocketMQ#393]
16-11-02 10:56:03 ERROR PullMessageService - pullKernelImpl exception
com.alibaba.rocketmq.remoting.exception.RemotingTooMuchRequestException: the channel[[id: 0xee8c3dd1, /10.126.88.100:43585 => /10.126.88.100:10911]] is not writable now
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:627) ~[rocketmq-remoting-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessageAsync(MQClientAPIImpl.java:382) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:363) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:216) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:512) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:77) [rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:93) [rocketmq-client-3.4.6.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-11-02 10:56:08 ERROR PullMessageService - pullKernelImpl exception
com.alibaba.rocketmq.remoting.exception.RemotingTooMuchRequestException: the channel[[id: 0xee8c3dd1, /10.126.88.100:43585 => /10.126.88.100:10911]] is not writable now
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:627) ~[rocketmq-remoting-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessageAsync(MQClientAPIImpl.java:382) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:363) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:216) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:512) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:77) [rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:93) [rocketmq-client-3.4.6.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-11-02 10:56:08 ERROR PullMessageService - pullKernelImpl exception
com.alibaba.rocketmq.remoting.exception.RemotingTooMuchRequestException: the channel[[id: 0xee8c3dd1, /10.126.88.100:43585 => /10.126.88.100:10911]] is not writable now
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:627) ~[rocketmq-remoting-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessageAsync(MQClientAPIImpl.java:382) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:363) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:216) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:512) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:77) [rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:93) [rocketmq-client-3.4.6.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-11-02 10:56:08 ERROR PullMessageService - pullKernelImpl exception
com.alibaba.rocketmq.remoting.exception.RemotingTooMuchRequestException: the channel[[id: 0xee8c3dd1, /10.126.88.100:43585 => /10.126.88.100:10911]] is not writable now
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:627) ~[rocketmq-remoting-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessageAsync(MQClientAPIImpl.java:382) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:363) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:216) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:512) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:77) [rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:93) [rocketmq-client-3.4.6.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-11-02 10:56:08 ERROR PullMessageService - pullKernelImpl exception
com.alibaba.rocketmq.remoting.exception.RemotingTooMuchRequestException: the channel[[id: 0xee8c3dd1, /10.126.88.100:43585 => /10.126.88.100:10911]] is not writable now
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:627) ~[rocketmq-remoting-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessageAsync(MQClientAPIImpl.java:382) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.pullMessage(MQClientAPIImpl.java:363) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullAPIWrapper.pullKernelImpl(PullAPIWrapper.java:216) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.pullMessage(DefaultMQPushConsumerImpl.java:512) ~[rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.pullMessage(PullMessageService.java:77) [rocketmq-client-3.4.6.jar:na]
	at com.alibaba.rocketmq.client.impl.consumer.PullMessageService.run(PullMessageService.java:93) [rocketmq-client-3.4.6.jar:na]
	at java.lang.Thread.run(Thread.java:662) [na:1.6.0_45]
16-11-02 10:56:09 INFO MQClientFactoryScheduledThread - send heart beat to broker[broker-a 0 10.126.88.100:10911] success

**Comment by Jaskey** [comment]
How do you produce this problem. RemotingTooMuchRequestException is thrown when so many remoting request are sent in a very short time that semaphore can not be acquied in a given time.

**Comment by a11123939** [comment]
mq 3.4.6 benchmark . pull message client log error .

**Comment by a11123939** [comment]
6-11-02 18:08:12 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:12 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:17 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:17 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:17 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:17 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:22 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:22 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:22 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:27 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:32 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception
16-11-02 18:08:37 ERROR PullMessageService - pullKernelImpl exception

the time have  regular pattern . Every 5 seconds or 15s or 35s . most time is 5 seconds

**Comment by a11123939** [comment]
# **when the consumer offset update set to 30*1000 ms**
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:15:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:18:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:19:58 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception
16-11-02 19:20:28 ERROR PullMessageService - pullKernelImpl exception

**Comment by vongosling** [comment]
You triggered written limitation,please check your code.In our next version,we will optimize here, add WRITE_BUFFER_WATER_MARK config~

**Comment by a11123939** [comment]
# this is because benchmarkTest topic have 1000 queues,update consumer offset may cause netty buffer is full and canot write
