### ISSUE TITLE
water mask功能中类型转换错误

### ISSUE THREAD

**Issue by jingbanghu** [alibaba/RocketMQ#394]
运行报错：
2016-11-02 04:31:23 ERROR BrokerControllerScheduledThread1 - castRunnable exception, com.alibaba.rocketmq.broker.latency.FutureTaskExt
java.lang.ClassCastException: com.alibaba.rocketmq.broker.processor.PullMessageProcessor$2 cannot be cast to com.alibaba.rocketmq.remoting.netty.RequestTask
	at com.alibaba.rocketmq.broker.latency.BrokerFastFailure.castRunnable(BrokerFastFailure.java:104) ~[rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:422) [rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) [rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) [rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) [rocketmq-broker-3.5.8.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-11-02 04:31:23 ERROR BrokerControllerScheduledThread1 - printWaterMark error.
java.lang.NullPointerException: null
	at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills(BrokerController.java:423) ~[rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController.headSlowTimeMills4PullThreadPoolQueue(BrokerController.java:436) ~[rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController.printWaterMark(BrokerController.java:441) ~[rocketmq-broker-3.5.8.jar:na]
	at com.alibaba.rocketmq.broker.BrokerController$4.run(BrokerController.java:260) ~[rocketmq-broker-3.5.8.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_102]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by jingbanghu** [comment]
期间大量报这样的错误：
2016-11-02 04:31:33 WARN ClientManageThread_4 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2506, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_1 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2508, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_6 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2510, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_11 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2522, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_13 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2524, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_6 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2526, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:33 WARN ClientManageThread_10 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=2527, requestOffset=71903, storeOffset=71904
2016-11-02 04:31:37 WARN PullMessageThread_4 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:53642, key=BSJ-POS@CID-BSJ-STORM, queueId=1646, requestOffset=71911, storeOffset=71912
2016-11-02 04:31:49 INFO BrokerControllerScheduledThread1 - dispatch behind commit log 345349 bytes
2016-11-02 04:31:49 INFO BrokerControllerScheduledThread1 - slave fall behind master, how much, 98523226367 bytes
2016-11-02 04:31:50 INFO BrokerControllerScheduledThread1 - register broker to name server 10.116.67.48:9876 OK
2016-11-02 04:31:58 WARN ClientManageThread_4 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=1884, requestOffset=71912, storeOffset=71913
2016-11-02 04:31:58 WARN ClientManageThread_14 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=1903, requestOffset=71912, storeOffset=71913
2016-11-02 04:31:58 WARN ClientManageThread_16 - [NOTIFYME]update consumer offset less than store. clientHost=10.27.29.127:41384, key=BSJ-POS@CID-BSJ-STORM, queueId=1897, requestOffset=71912, storeOffset=71913

**Comment by vongosling** [comment]
the same question as https://github.com/alibaba/RocketMQ/pull/379
