### ISSUE TITLE
3.5.8 client consumer cannot shutdown . because  of CleanExpireMsgExecutors donnot shutdown

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#405]
2016-11-08 11:25:28
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode):

"DestroyJavaVM" #27 prio=5 os_prio=0 tid=0x000000005b95e000 nid=0xd04 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"CleanExpireMsgScheduledThread_1" #16 prio=5 os_prio=0 tid=0x00000000596a6800 nid=0x1d1c waiting on condition [0x000000005a8ce000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000def1c758> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00000000586fd000 nid=0x1c40 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000058685800 nid=0x1100 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000000058684800 nid=0x2328 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x000000005725e800 nid=0x16c0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000005866b000 nid=0x1ed8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000005725a800 nid=0x1c0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x0000000057239800 nid=0x1128 in Object.wait() [0x00000000583cf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000def7e8a0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000def7e8a0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000571f2800 nid=0x2114 in Object.wait() [0x000000005865f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000def8f748> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000000def8f748> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=2 tid=0x00000000571eb000 nid=0x2120 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x000000000246d000 nid=0x1cb4 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x000000000246e800 nid=0x688 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002470000 nid=0x1d08 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002471800 nid=0x504 runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x000000005872a800 nid=0x1624 waiting on condition 

JNI global references: 281

**Comment by vongosling** [comment]
Thank you, the latest version will fix this problem

**Comment by vongosling** [comment]
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)
