### ISSUE TITLE
About consumer shutdown problem 

### ISSUE THREAD

**Issue by Ah39** [alibaba/RocketMQ#407]
this.consumeMessageService.shutdown();
                this.persistConsumerOffset();
                this.mQClientFactory.unregisterConsumer(this.defaultMQPushConsumer.getConsumerGroup());
                this.mQClientFactory.shutdown();
##     consumerMessageService.shutdown is not a block function ,may cause the Consumer have updated consumer Offset , consumeMessageService is still consuming Message 

in this.mQClientFactory.shutdown(); 
      this.mQClientAPIImpl.shutdown();
       this.rebalanceService.shutdown();

    `2016-11-08 16:53:48 INFO main - shutdown thread NettyEventExecuter interrupt false
    2016-11-08 16:53:48 INFO NettyClientSelector_1 - closeChannel: close the connection to remote    address[10.126.88.100:10911] result: true
    2016-11-08 16:53:48 INFO main - join thread NettyEventExecuter eclipse time(ms) 0 90000
    2016-11-08 16:53:48 INFO main - shutdown thread RebalanceService interrupt false
    2016-11-08 16:53:48 INFO NettyClientSelector_1 - closeChannel: close the connection to remote   address[10.126.84.66:10911] result: true
    2016-11-08 16:53:48 INFO NettyClientSelector_1 - closeChannel: close the connection to remote address[10.126.84.66:9876] result: true
    2016-11-08 16:53:48 INFO NettyClientSelector_1 - closeChannel: close the connection to remote address[10.126.88.100:10909] result: true
    2016-11-08 16:53:53 WARN RebalanceService - invokeSync: wait response timeout exception, the channel[10.126.88.100:10909]
    2016-11-08 16:53:53 WARN RebalanceService - fetchConsumeOffsetFromBroker exception, MessageQueue [topic=BenchmarkTest, brokerName=broker-a, queueId=616]
    com.alibaba.rocketmq.remoting.exception.RemotingTimeoutException: wait response on the    channel <10.126.88.100:10909> timeout, 5000(ms)
	at      com.alibaba.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:290) ~[classes/:na]
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:341) ~[classes/:na]
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.queryConsumerOffset(MQClientAPIImpl.java:713) ~[classes/:na]
	at com.alibaba.rocketmq.client.consumer.store.RemoteBrokerOffsetStore.fetchConsumeOffsetFromBroker(RemoteBrokerOffsetStore.java:237) ~[classes/:na]
	at com.alibaba.rocketmq.client.consumer.store.RemoteBrokerOffsetStore.readOffset(RemoteBrokerOffsetStore.java:95) ~[classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.RebalancePushImpl.computePullFromWhere(RebalancePushImpl.java:146) [classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.updateProcessQueueTableInRebalance(RebalanceImpl.java:374) [classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:296) [classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:221) [classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:913) [classes/:na]
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:889) [classes/:na]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:47) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]`
# Why clientAPI shutdown before rebalanceService??
the code may cause netty channel have closed . rebalanceService is still call netty channel send data .

**Comment by vongosling** [comment]
please note your log format in markdown next time~

**Comment by zhouxinyu** [comment]
Yes, there may be some exception logs..

And, any contributions are welcome~
