### ISSUE TITLE
FAQ: No route info of this topic, TopicABC

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#44]
## 可能产生的原因
* Broker没有正确连接到Name Server

	或

* Producer没有正确连接到Name Server

	或

* Broker禁止自动创建Topic，且用户没有通过手工方式创建Topic

## 解决方案一（推荐阿里内部用户使用）
到MetaQ控制台或者Spass控制台上申请Topic

## 解决方案二（推荐开源社区用户使用）
* 确保Producer、Broker正确连接到Name Server，且是同一个Name Server集群

**Comment by eyechen** [comment]
producer 引用的 fastjson 版本要为 1.1.41  ，否则也会报这个错误；

**Comment by krisjin** [comment]
在启动borker之前需要指定nameserver地址:
export NAMESRV_ADDR=Your_name_IP:9876

**Comment by 24king** [comment]
启动方式指定一下nameserver
> [limix@LIMIX bin]$ ./mqbroker -n "192.168.1.103:9876" -c ../conf/2m-2s-async/broker-a.properties &
[2] 7336
[limix@LIMIX bin]$ load config properties file OK, ../conf/2m-2s-async/broker-a.properties
**The broker[broker-a, 192.168.1.103:10911] boot success. and name server is 192.168.1.103:9876**

**Comment by panpanxu** [comment]
先启动nameserv再启动broker。

**Comment by manyi100** [comment]
请检查确认防火墙是否正确关闭。

**Comment by felayman** [comment]
@krisjin  thanks。
在启动borker之前需要指定nameserver地址:
export NAMESRV_ADDR=Your_name_IP:9876

**Comment by canghaiyisu666** [comment]
docker run -p 9876:9876 -p 10911:10911 --rm vongosling/rocketmq

通过这种方式启动之后给producer设置IP:9876，报错为：connect to <172.17.0.2:10911> failed
修改producer的设置为IP:10911 后报错为No route info of this topic

**Comment by canghaiyisu666** [comment]
问题以解决： 在producer中设置了nameserverIP为宿主机IP之后，docker容器内部返回的brokerIP为docker的IP， 把producer放在宿主机上执行则可以解决。
ps：建议在docker的兼容性上再做一些改进

**Comment by zouterry** [comment]
export NAMESRV_ADDR=Your_name_IP:9876  在哪里哪个文件里面配置的

**Comment by zcgewu** [comment]
rocketmq单机模式部署在公网上，example中的producer还是报该错误。broker已成功启动，且已连接nameserv。producer通过producer.setNamesrvAddr("121.40.xx.16:9876") 连接nameserv。9876和10911端口都可以telnet。
具体配置如下：
brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
namesrvAddr=121.40.xx.16:9876
brokerIP1=121.40.xx.16
listenPort=10911
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true

**Comment by jiu30** [comment]
问题1: 我断点跟踪了下在这个函数：  private SendResult sendDefaultImpl 的最后面又这样一段抛异常的代码  
 throw new MQClientException("No route info of this topic, " + msg.getTopic()
                + FAQUrl.suggestTodo(FAQUrl.NO_TOPIC_ROUTE_INFO), null);

那就是 只要进入这个函数，都会抛出异常，这样合理吗？不理解，求解！  谢谢！

问题2： 我在window7下通过命令：  start/b   xxx.exe  先打开mqnamesrv.exe, 再打开 mqbroker.exe,    我通过 jps 查看端口后，可是通过telnet  没有一个可以打开 ，不知何故（防火墙已关闭）  请教了！！！！

**Comment by AndyLue** [comment]
还有在启动mqbroker.exe时,不要直接双击!而是应该在CMD中输入mqbroker.exe -n localhost:9876 (你自己设置的地址)

**Comment by gghaomm** [comment]
非MAVEN项目 可能是有JAR没有加  也会报这个错误的
 比如：fastjion-1.2.3.jar
可以通POM Dependency HIerarchy 来看差什么JAR

**Comment by mlj007** [comment]
docker 虚拟环境下，部署RocketMQ 会报错为：connect to <容器IP:10911> failed。因为docker 返回的IP不是与你请求的IP 不同，所以无法建立连接。临时解决办法：将NamesrvAddr 的IP地址换成docker 的IP ,并且将项目部署到docker虚拟环境内。正式环境建议不要使用docker虚拟机。

**Comment by MrLaughing** [comment]
你好，我也遇到了这个问题，Demo里运行Consumer没问题，Producer就会这样，但是我调了producer.getNamesrvAddr() 拿到的确实是127.0.0.1：9876 看了看楼上说的关于fastjson Demo里并没有这个关于这个的dependency 我本地repository里fastjson是1.2.3。不知道是哪里出了问题。如有建议还请帮助，谢谢！

**Comment by gummike** [comment]
在运行docker镜像 启动生成着报这个错误
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic, PushTopic

**Comment by zhx2015** [comment]
Hi, ALL!
我这里也碰到这个问题，报错：
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic, smsTopic
See https://github.com/alibaba/RocketMQ/issues/264 for further details.
        at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:570)
        at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:972)

但奇怪的是！不是一直报这个错！
而是10次测试发送消息中，可能会成功9次，偶尔出现1次报这个错。
有一种可能是网络延时导致，但ping nameserver机器IP长达2分钟，并没有发现网络断掉的情况。
不明白为什么会这样，如果我的服务器部署问题，那为什么大部分时候是可以发送消息，也可以消费的。
请帮我分析一下问题可能的原因，非常感谢！

**Comment by zhonghuahero** [comment]
我的服务是阿里云centos6.5单机，测试代码本机连远程
telnet 远程机公网IP 9876和10911都可以通
确认ns和br已启动

broker启动日志
The broker[hostname, 公网IP:10911] boot success. and name server is 公网IP:9876


本机（windows eclipse调试）测试代码
DefaultMQProducer producer = new DefaultMQProducer("rmq-group");
		producer.setNamesrvAddr("123.56.2.74:9876");
		producer.setInstanceName("rmq-instance");
		producer.setCreateTopicKey("TopicA-test");


DefaultMQPushConsumer consumer = new DefaultMQPushConsumer("rmq-group");

		consumer.setNamesrvAddr("123.56.2.74:9876");
		consumer.setInstanceName("rmq-instance");
		consumer.subscribe("TopicA-test", "TagA");


异常信息如下
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic, TopicA-test
See https://github.com/alibaba/RocketMQ/issues/44 for further details.
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:587)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)
	at com.hero.mq.Producer.main(Producer.java:24)

**Comment by zhonghuahero** [comment]
@zcgewu @zhx2015  请问两位问题解决了么？解决方案是什么？谢谢

**Comment by zhangconan** [comment]
单机环境的，win下，可以试试这样 mqbroker.exe -n localhost:9876 autoCreateTopicEnable=true

**Comment by sssxiahuyue** [comment]
最终的答案   如果确定nameserver 和 broker都启动并且配置无误，但是还是报No route info of this topic的错误，那我告诉你。。。**关掉双方的防火墙才是问题的关键**。我在这上边耗了两天的时间，终于解决了。其余的是按照官网来的   没搞什么autoCreateTopic

**Comment by jazzy09** [comment]
我是JAVA_OPTS设置的值太大了，导致broker启动起来一会又被停掉了。

**Comment by wjweilovelife** [comment]
@sssxiahuyue  为什么关掉防火墙就好了，不是防火墙的端口已经开启了吗？为什么开启之后调不通？如果开启，有什么方法可以解决这个问题？

**Comment by wjweilovelife** [comment]
@sssxiahuyue  解决了，开启防火墙，不仅要启动9876端口，还要开启10911端口。

**Comment by GitHeP** [comment]
如果是在别的机器上运行，rocketmq 中 exmaple 的例子，产生这个问题，暂时关掉服务器的防火墙就行了，autoCreateTopicEnable 默认就是为 true 的和这个没关系。

**Comment by pen4** [comment]
I use it in windows ,it also happened:
start to send message
com.alibaba.rocketmq.client.exception.MQClientException: No route info of this topic, test1

**Comment by huozhicheng** [comment]
查看一下集群状态，也有可能是broker没有注册到namesrv
sh mqadmin clusterList -n xxx.xx.xx.xx:9876

**Comment by zmatsh** [comment]
https://firsh.me/2017/07/19/rocketmq-p-c/ 这里有讲解

**Comment by duomu** [comment]
windows无法远程访问虚拟机上的rocketmq服务，在rocketmq-console查了下远程主机上的provider和consumer都没有注册成功，可是虚拟机上面的provider和consumer可以正常注册和收发消息，已经把虚拟机上的防火墙关了，实在是不知道还有什么原因了 @pen4 这位同学，你问题解决了没？

**Comment by duomu** [comment]
@breakEval13 这位同学，我照着你那篇文章搭建的，还是无法远程访问虚拟机上的mq服务

**Comment by goule1993** [comment]
@duomu 如果解决了记得回复我下，我也是这个问题，O(∩_∩)O谢谢

**Comment by duomu** [comment]
@goule1993 我的问题解决了，写到博客里啦，你看看对你有没有帮助
http://blog.csdn.net/c_yang13/article/details/76836753

**Comment by jaychang9** [comment]
整理下问题不错，感谢大家分析

**Comment by manysy** [comment]
还有一种可能，就是jar包冲突，4.1.0-incubating依赖的netty版本是netty-all-4.0.36-final.jar，

我的spring cloud依赖的netty的模块的版本是4.0.27，在rocketmq-client.log日志中会看到报错日志：

java.lang.NoSuchMethodError: io.netty.util.internal.RecyclableArrayList.insertSinceRecycled()Z

所以去掉低版本的netty模块依赖就行了

![Uploading TIM图片20170929121009.png…]()

**Comment by manysy** [comment]
不知道图片为啥没有上传成功，贴出代码来，去掉低版本的netty模块依赖即可：

compile("org.springframework.cloud:spring-cloud-starter-eureka") {
    	exclude group: 'io.netty', module: 'netty-buffer'
    	exclude group: 'io.netty', module: 'netty-codec-http'
    	exclude group: 'io.netty', module: 'netty-handler'
    	exclude group: 'io.netty', module: 'netty-transport-native-epoll'
    	exclude group: 'io.netty', module: 'netty-codec'
    	exclude group: 'io.netty', module: 'netty-common'
    	exclude group: 'io.netty', module: 'netty-transport'
	}

**Comment by 0jas0** [comment]
为什么生产者只要一启动，nameServer就报这个错
2018-01-04 22:07:19 WARN NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: exceptionCaught exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_72]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_72]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_72]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_72]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_72]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
2018-01-04 22:07:19 INFO NettyServerSelector_3_1 - closeChannel: close the connection to remote address[192.168.0.102:6072] result: true
2018-01-04 22:07:19 INFO NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.0.102:6072]
2018-01-04 22:07:19 INFO NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.0.102:6072]
2018-01-04 22:07:27 INFO NSScheduledThread1 - --------------------------------------------------------
2018-01-04 22:07:27 INFO NSScheduledThread1 - configTable SIZE: 0

**Comment by 0jas0** [comment]
为什么生产者只要一启动，nameServer就报这个错
2018-01-04 22:07:19 WARN NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: exceptionCaught exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_72]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_72]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_72]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_72]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_72]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
2018-01-04 22:07:19 INFO NettyServerSelector_3_1 - closeChannel: close the connection to remote address[192.168.0.102:6072] result: true
2018-01-04 22:07:19 INFO NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: channelInactive, the channel[192.168.0.102:6072]
2018-01-04 22:07:19 INFO NettyServerWorkerThread_1 - NETTY SERVER PIPELINE: channelUnregistered, the channel[192.168.0.102:6072]
2018-01-04 22:07:27 INFO NSScheduledThread1 - --------------------------------------------------------
2018-01-04 22:07:27 INFO NSScheduledThread1 - configTable SIZE: 0
