### ISSUE TITLE
FAQ: 未收录异常处理办法

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#48]

**Comment by weamor** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: No route info for this topic, TopicTestjjj 

这个问题是怎么导致的，如何解决？

**Comment by stomeMan** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [5]ms, Topic: TopicTest, BrokersSent: [YXT-015-GW, null, null]
See https://github.com/alibaba/RocketMQ/issues/50 for further details.
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:578)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)
	at com.alibaba.rocketmq.example.quickstart.Producer.main(Producer.java:40)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: java.lang.NullPointerException, com.alibaba.rocketmq.broker.processor.AdminBrokerProcessor.processRequest(AdminBrokerProcessor.java:86)
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:404)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:308)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:289)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:679)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:500)
	... 4 more

**Comment by stomeMan** [comment]
please help me,I'm new one to RockMQ

**Comment by vintagewang** [comment]
@stomeMan   初步看 是客户端与服务器版本不一致。

**Comment by stomeMan** [comment]
如何查询版本呢，服务器版本如何查看，我如何能搞到和服务器版本一直的客户端，在git上下载下来都是最新的啊

**Comment by stomeMan** [comment]
刚才查过了版本都是3.2.6，大神们有有什么其他原因会导致这个错误啊

**Comment by arvinli** [comment]
偶尔出现这样的异常。
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: the message is illegal, maybe length not matched.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:404)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:308)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:289)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:679)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:500)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)
	at com.taobao.metaq.client.MetaProducer.send(MetaProducer.java:126)
	at com.taobao.metaq.client.MetaProducer$$FastClassBySpringCGLIB$$e76ee245.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.aliyun.app.common.rpclog.metaq.MetaqRpcLogInterceptor.invoke(MetaqRpcLogInterceptor.java:103)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at com.taobao.metaq.client.MetaProducer$$EnhancerBySpringCGLIB$$70c3692.send(<generated>)

**Comment by kuangzuoqiang** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: The producer service state not OK, CREATE_JUST
See https://github.com/alibaba/RocketMQ/issues/43 for further details.

**Comment by kuangzuoqiang** [comment]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: no consumer for this group, CID_LIKER365_QUGG_MEMBER
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getConsumerIdListByGroup(MQClientAPIImpl.java:681) ~[rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:1109) [rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:293) [rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:257) [rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:258) [rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:992) [rocketmq-client-3.2.5.jar:?]
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:49) [rocketmq-client-3.2.5.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

总是报这个警告，由spring启动报这个错，单独用class测试时并没有

**Comment by ronyongxian** [comment]
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.11 CQ:  0.91 INDEX:  0.91, maybe your broker machine memory too small.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:404)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:308)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:289)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:679)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:500)
	... 9 more

查看磁盘和内存，都还有空间。。。

**Comment by sinlmao** [comment]
Caused by: com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed
	at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:641)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1298)
	at com.alibaba.rocketmq.client.impl.MQAdminImpl.createTopic(MQAdminImpl.java:78)
	... 4 more

createTopic出错，控制台创建也是这个问题........

**Comment by seagle-yuan** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: the specified topic is blank
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.Validators.checkTopic(Validators.java:63)
	at com.alibaba.rocketmq.client.Validators.checkMessage(Validators.java:118)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:480)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)

**Comment by hongwei24** [comment]
场景: consumer MQ 消息中，consumer角色转换Producer，发送消息时异常
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 4  DESC: not set any response code
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48

**Comment by mrtaiqichao** [comment]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 2 DESC: too many requests and system thread pool busy, please try another server
n-For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
n-at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:421)
n-at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:325)
n-at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:306)
n-at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:707)
n-at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:520)
n-at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1074)
n-at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1068)
n-at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:122)
n-at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.send(ProducerImpl.java:153)
@vintagewang

**Comment by enjoyEC** [comment]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 2  DESC: [TIMEOUT_CLEAN_QUEUE]broker busy, start flow control for a while, period in queue: 242ms, size of queue: 293

**Comment by baixiongfei** [comment]
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 2 DESC: [REJECTREQUEST]system busy, start flow control for a while,period in queue: 200ms, size of queue: 32

**Comment by cr2121** [comment]
2017-01-05 10:34:08,166 WARN [RebalanceService] - getConsumerIdListByGroup exception, 10.174.141.250:10911 orderserver_order_goods_status_change%crm - (MQClientInstance.java:1027)
com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: no consumer for this group, orderserver_order_goods_status_change%crm
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getConsumerIdListByGroup(MQClientAPIImpl.java:640) ~[rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:1025) [rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:282) [rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:248) [rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:250) [rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:925) [rocketmq-client-3.2.6.jar!/:?]
        at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:49) [rocketmq-client-3.2.6.jar!/:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

启动时几乎都要报这个问题

**Comment by huisongyang** [comment]
`get Topic [PADCLEAR_TO_FOSS] RouteInfoFromNameServer is not exist value
17-04-15 14:44:06,371 WARN RocketmqClient(635) - updateTopicRouteInfoFromNameServer Exception
com.alibaba.rocketmq.client.exception.MQClientException: CODE: 17  DESC: No topic route info in name server for the topic: PADCLEAR_TO_FOSS
See https://github.com/alibaba/RocketMQ/issues/38 for further details.
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1315)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:573)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:549)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.findConsumerIdList(MQClientInstance.java:1019)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.rebalanceByTopic(RebalanceImpl.java:282)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceImpl.doRebalance(RebalanceImpl.java:248)
	at com.alibaba.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.doRebalance(DefaultMQPushConsumerImpl.java:250)
	at com.alibaba.rocketmq.client.impl.factory.MQClientInstance.doRebalance(MQClientInstance.java:925)
	at com.alibaba.rocketmq.client.impl.consumer.RebalanceService.run(RebalanceService.java:49)
	at java.lang.Thread.run(Thread.java:662)`

服务器明明有topic，之前也消费成功，重启就不行了

**Comment by buttre** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: select message queue return null.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:870)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:842)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:836)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:164)
	at com.alibaba.middleware.race.rocketmq.Producer.main(Producer.java:51)

**Comment by franknew** [comment]
com.alibaba.rocketmq.client.exception.MQClientException:“the specified group[test version] contains illegal characters, allowing only ^[%|a-zA-Z0-9_-]+$
