### ISSUE TITLE
创建topic的报connect to <null> failed

### ISSUE THREAD

**Issue by zhtjava** [alibaba/rocketmq#505]
com.alibaba.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed
        at com.alibaba.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:641)
        at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.getTopicListFromNameServer(MQClientAPIImpl.java:1324)
        at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExtImpl.fetchAllTopicList(DefaultMQAdminExtImpl.java:397)
        at com.alibaba.rocketmq.tools.admin.DefaultMQAdminExt.fetchAllTopicList(DefaultMQAdminExt.java:258)
        at com.alibaba.rocketmq.tools.command.topic.TopicListSubCommand.execute(TopicListSubCommand.java:142)
        at com.alibaba.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:180)
        at com.alibaba.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:125)

执行sh mqadmin topicList -n 10.79.1.20:9876报上面的错误

brokerClusterName=rocketmq-cluster
brokerName=broker-a
brokerId=0
namesrvAddr=10.79.1.19:9876;10.79.1.20:9876
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
#flushDiskType=ASYNC_FLUSH
diskMaxUsedSpaceRatio=88
storePathRootDir=/opt/alibaba-rocketmq/data
storePathCommitLog=/opt/alibaba-rocketmq/data/commitlog
storePathConsumeQueue=/opt/alibaba-rocketmq/data/consumequeue
storePathIndex=/opt/alibaba-rocketmq/data/index
storeCheckpoint=/opt/alibaba-rocketmq/data/checkpoint
abortFile=/opt/alibaba-rocketmq/data/abort
maxMessageSize=65536

**Comment by vongosling** [comment]
请参考问问题 #108
