### ISSUE TITLE
UnknownHostException producer.start 的时候，取了我本机的 hostname，报错如下

### ISSUE THREAD

**Issue by monkeycraps** [alibaba/RocketMQ#63]
Caused by: java.net.UnknownHostException: monc.me: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)

**Comment by monkeycraps** [comment]
我在实用  ons 的时候也遇到一样的问题 
我的系统是 
Darwin monc.me 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

**Comment by vintagewang** [comment]
https://github.com/alibaba/RocketMQ/issues/64

**Comment by iMinusMinus** [comment]
报这个错也叫我到这个页面，坑啊！
Caused by: com.alibaba.rocketmq.client.exception.MQClientException: The producer group[******] has been created before, specify another name please.
See https://github.com/alibaba/RocketMQ/issues/63 for further details.
