### ISSUE TITLE
FAQ: 主机名不存在

### ISSUE THREAD

**Issue by vintagewang** [alibaba/RocketMQ#64]
### 问题原因
可能是无法正确获取主机名或者主机ip地址导致，请尝试使用以下命令来证实

    hostname

如果无法正常输出，就说明确实是此原因，如果可以正常输出，可能是其他原因，请尝试连续ONS客服或者提交Issue，由开发团队来定位问题

### 解决方案
    /etc/hosts
增加以下配置

    127.0.0.1 localhost

**Comment by xubing88** [comment]
请问 这种情况怎么处理；
com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [84547]ms, Topic: TopicTest, BrokersSent: [WIN-20140418NAJ, null, null]
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:590)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1026)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:122)
	at com.bing.Producer.main(Producer.java:40)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.98 CQ:  0.98 INDEX:  0.98, maybe your broker machine memory too small.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:491)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:397)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:378)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:698)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:514)
	... 3 more

**Comment by xubing88** [comment]
com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [374]ms, Topic: TopicTest, BrokersSent: [bing, null, null]
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:590)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1026)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:122)
	at com.bing.Producer.main(Producer.java:40)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.98 CQ:  0.98 INDEX:  0.98, maybe your broker machine memory too small.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:491)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:397)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:378)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:698)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:514)
	... 3 more
请问这个怎么处理？（之前我提交的问题怎么没了。）

**Comment by vintagewang** [comment]
亲， 不要在这里提交， 单独建立个issue

**Comment by lane-cn** [comment]
对于多网卡的机器，broker可能会把错误的IP地址汇报给name server，造成client找不到broker，无法发送消息。可以在启动时创建config文件，设置brokerIP1=10.130.X.X，启动broker:  ./mqbroker -c ./conf.txt &

**Comment by whatsmore** [comment]
whats@whats-To-be-filled-by-O-E-M:~/workspace/alibaba-rocketmq/bin$ sh mqnamesrv
java.lang.ExceptionInInitializerError
	at com.alibaba.rocketmq.namesrv.NamesrvStartup.main0(NamesrvStartup.java:125)
	at com.alibaba.rocketmq.namesrv.NamesrvStartup.main(NamesrvStartup.java:70)
Caused by: java.lang.RuntimeException: InetAddress java.net.InetAddress.getLocalHost() throws UnknownHostException
See https://github.com/alibaba/RocketMQ/issues/64 for further details.
	at com.alibaba.rocketmq.common.MixAll.localhost(MixAll.java:458)
	at com.alibaba.rocketmq.common.MixAll.<clinit>(MixAll.java:82)
	... 2 more
Caused by: java.net.UnknownHostException: whats-To-be-filled-by-O-E-M: whats-To-be-filled-by-O-E-M: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at com.alibaba.rocketmq.common.MixAll.localhost(MixAll.java:454)
	... 3 more
Caused by: java.net.UnknownHostException: whats-To-be-filled-by-O-E-M: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 4 more
whats@whats-To-be-filled-by-O-E-M:~/workspace/alibaba-rocketmq/bin$ hostname
whats-To-be-filled-by-O-E-M

**Comment by patrick-unicorn** [comment]
注意：在MAC上默认的hostname是主机用户名，比如："Unicorns-MacBook-Pro.local"，此时需要在/etc/hosts中添加一行：

```
127.0.0.1   Unicorns-MacBook-Pro.local
```

之后执行`ping Unicorns-MacBook-Pro.local`可以看到正常的PING信息了。
此时再启动应用程序即可。
