### ISSUE TITLE
本机启动生产者报错，跪求如何解决

### ISSUE THREAD

**Issue by xubing88** [alibaba/RocketMQ#66]
com.alibaba.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [75]ms, Topic: TopicTest, BrokersSent: [bing, null, null]
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:590)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1026)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:122)
	at com.bing.Producer.main(Producer.java:40)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14  DESC: service not available now, maybe disk full, CL:  0.98 CQ:  0.98 INDEX:  0.98, maybe your broker machine memory too small.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/64
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:491)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:397)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:378)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:698)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:514)
	... 3 more

**Comment by xubing88** [comment]
需要修改mqbroker.xml，里面的参数：
<options>
		<-Xms512m></-Xms512m>
		<-Xmx1g></-Xmx1g>
		<-XX:NewSize>256M</-XX:NewSize>
		<-XX:MaxNewSize>1024M</-XX:MaxNewSize>
		<-XX:PermSize>128M</-XX:PermSize>
		<-XX:MaxPermSize>512M</-XX:MaxPermSize>
	</options>
调大一点就ok了，具体原理还需要研究一下

**Comment by vintagewang** [comment]
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 14 DESC: service not available now, maybe disk full, CL: 0.98 CQ: 0.98 INDEX: 0.98, maybe your broker machine memory too small.


服务器磁盘满了

**Comment by yinbin1yd** [comment]
这个问题把服务器与客户端版本改成一致的就可以了

**Comment by SpruceWang** [comment]
我也遇到了这个问题，按照 xubing88 的方法修改后就OK了，非常感谢。
