### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ccvcd** [alibaba/RocketMQ#77]
rocketmq版本：3.2.4

SLF4J: Failed toString() invocation on an object of type [java.util.TreeMap]
java.util.ConcurrentModificationException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1115)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1151)
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1146)
	at java.util.AbstractMap.toString(AbstractMap.java:518)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:305)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:231)
	at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:463)
	at com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:183)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

引起的代码，
                log.warn(
                    "processQueue is dropped without process consume result. messageQueue={}, msgTreeMap={}, msgs={}",
                    new Object[] { messageQueue, processQueue.getMsgTreeMap(), msgs });

**Comment by vintagewang** [comment]
是问题。 不过不影响消息中间件的正常工作。 属低优先级bug， 下个版本修复。

**Comment by vongosling** [comment]
please using  version 3.4.6. and later versions
