### ISSUE TITLE
压力测试消息发送失败，提示Create maped file failed, please make sure OS and JDK both 64bit.

### ISSUE THREAD

**Issue by leopardoooo** [alibaba/RocketMQ#98]
压力测试的时候，经常出现发送失败的情况，收到1W多条发送失败的异常信息，根据错误提示以及异常内容提示的issues50和issues48，我并不能确定问题的根本原因。希望作者能解答一下，另外我的服务器配置是：4master-nosalve，对应的brokerName分别为broker-a, broker-b, broker-c, broker-d，2台nameserver，6台消息生产者的web程序，会根据业务发送不同的topic消息。我能确定的是Broker并没有挂。期待您的回复！谢谢！

com.alibaba.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [5]ms, Topic: PRESENT_ANCHOR_EXP, BrokersSent: [broker-a, broker-c, broker-a]
See https://github.com/alibaba/RocketMQ/issues/50 for further details.
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:578)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1031)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1025)
	at com.alibaba.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:95)
	at com.easyooo.show.consumer.service.ExpCalService.doService(ExpCalService.java:176)
	at com.easyooo.show.consumer.service.ExpCalService.doServiceForConsume(ExpCalService.java:105)
	at com.easyooo.show.consumer.service.ExpCalService$$FastClassBySpringCGLIB$$4e6e0776.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:633)
	at com.easyooo.show.consumer.service.ExpCalService$$EnhancerBySpringCGLIB$$cf34b652.doServiceForConsume(<generated>)
	at com.easyooo.show.consumer.listener.GiftExpListener.doProcessMessage(GiftExpListener.java:25)
	at com.easyooo.show.consumer.listener.GiftExpListener.doProcessMessage(GiftExpListener.java:17)
	at com.easyooo.show.consumer.impl.ContextDispatchMessageListener$1.doCallback(ContextDispatchMessageListener.java:43)
	at com.easyooo.show.consumer.impl.ContextDispatchMessageListener$1.doCallback(ContextDispatchMessageListener.java:38)
	at com.easyooo.show.commons.support.ProxyUtil.doProxy(ProxyUtil.java:46)
	at com.easyooo.show.consumer.impl.ContextDispatchMessageListener.doParseMessage(ContextDispatchMessageListener.java:38)
	at com.easyooo.show.consumer.impl.AbstractDispatchMessageListener.processMessages(AbstractDispatchMessageListener.java:50)
	at com.easyooo.show.consumer.impl.AbstractDispatchMessageListener.consumeMessage(AbstractDispatchMessageListener.java:43)
	at com.alibaba.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: create maped file failed, please make sure OS and JDK both 64bit.
For more information, please visit the url, https://github.com/alibaba/RocketMQ/issues/48
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:404)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:308)
	at com.alibaba.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:289)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:679)
	at com.alibaba.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:500)
	... 31 more

**Comment by leopardoooo** [comment]
我从发送失败的消息中发现，所有失败的都是broker-a和broker-c， 我从服务器日志文件storeerror.log中发现了，这两台每隔30秒都会输出如下异常，这和https://github.com/alibaba/RocketMQ/issues/81 ，描述的一致，但我部署的结构不是主从复制，而是4Master，没有备机。
2015-05-07 21:34:18 WARN FlushCommitLogService - findMapedFileByOffset offset not matched, request Offset: 41875931136, index: 39, mapedFileSize: 1073741824, mapedFiles count: 39, StackTrace: 
        java.lang.Thread.getStackTrace(Thread.java:1552)
        com.alibaba.rocketmq.common.UtilAll.currentStackTrace(UtilAll.java:63)
        com.alibaba.rocketmq.store.MapedFileQueue.findMapedFileByOffset(MapedFileQueue.java:467)
        com.alibaba.rocketmq.store.MapedFileQueue.commit(MapedFileQueue.java:442)
        com.alibaba.rocketmq.store.CommitLog$FlushRealTimeService.run(CommitLog.java:772)
        java.lang.Thread.run(Thread.java:745)

**Comment by leopardoooo** [comment]
附带我的broker部署图：
![1](https://cloud.githubusercontent.com/assets/4019562/7516351/5b1e2d9a-f501-11e4-88cd-d72dea7ac338.png)

**Comment by lizhanhui** [comment]
看一下store.log, 有没有Error， 比如这个错误信息有没有： create mapedfile exception.

**Comment by leopardoooo** [comment]
刚根据你的提示，查看了/root/rocketmqlogs/store.log日志文件，不停的抛出了异常，异常如下：
![2](https://cloud.githubusercontent.com/assets/4019562/7529192/233d51d8-f567-11e4-864b-65778aca290e.png)

**Comment by leopardoooo** [comment]
经过一晚上的压力测试，broker没有挂掉，问题解决。解决方案其实很简单，主要是linux的MAX_MAP_COUNT值太小了，设置大一点就OK。另外还有几个参数需要设置，具体可以参考RocketMQ的发布包中的$ROCKETMQ_HOME/bin/os.sh文件！

非常感谢RMQ团队 @lizhanhui 的指导！
